[package]
authors = ["Hayato Ito <hayato@google.com>"]
description = "A simple, fast, opinioned static site generator"
edition = "2018"
license = "Apache-2.0"
name = "site"
readme = "README.md"
repository = "https://github.com/hayatoito/site"
version = "0.1.5-alpha.0"

[dependencies]
glob = "0.3.0"
lazy_static = "1.4.0"
log = "0.4.14"
loggerv = "0.7.2"
pulldown-cmark = "0.8.0"
rayon = "1.5.0"
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_yaml = "0.8.17"
structopt = "0.3.21"
tera = "1.8.0"
toml = "0.5.8"
unicode-width = "0.1.8"
walkdir = "2.3.2"
anyhow = "1.0.40"

[dependencies.chrono]
features = ["serde"]
version = "0.4.19"
