[package]
authors = ["Hayato Ito <hayato@google.com>"]
description = "A simple, fast, opinioned static site generator"
edition = "2018"
license = "MIT"
name = "site"
repository = "https://github.com/hayatoito/site"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
glob = "0.2.11"
lazy_static = "1.2.0"
log = "0.4.6"
loggerv = "0.7.1"
pulldown-cmark = "0.2.0"
rayon = "1.0.3"
regex = "1.0.6"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_yaml = "0.8.7"
structopt = "0.2.13"
tera = "0.11.20"
toml = "0.4.9"
unicode-width = "0.1.5"
walkdir = "2.2.7"

[dependencies.chrono]
features = ["serde"]
version = "0.4"
