[package]
authors = ["Hayato Ito <hayato@google.com>"]
description = "A simple, fast, opinioned static site generator"
edition = "2021"
license = "Apache-2.0"
name = "site"
readme = "README.md"
repository = "https://github.com/hayatoito/site"
version = "0.5.0"

[dependencies]
anyhow = "1.0.75"
glob = "0.3.1"
lazy_static = "1.4.0"
log = "0.4.21"
pretty_env_logger = "0.5.0"
pulldown-cmark = "0.9.3"
rayon = "1.9.0"
regex = "1.10.2"
serde = { version = "1.0.192", features = ["derive"] }
structopt = "0.3.26"
tera = "1.19.1"
toml = "0.8.10"
unicode-width = "0.1.11"
walkdir = "2.5.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.31"
