[package]
authors = ["Hayato Ito <hayato@google.com>"]
description = "A simple, fast, opinioned static site generator"
edition = "2021"
license = "Apache-2.0"
name = "site"
readme = "README.md"
repository = "https://github.com/hayatoito/site"
version = "0.3.0"

[dependencies]
anyhow = "1.0.48"
glob = "0.3.0"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
pulldown-cmark = "0.8.0"
rayon = "1.5.1"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
structopt = "0.3.25"
tera = "1.15.0"
toml = "0.5.8"
unicode-width = "0.1.9"
walkdir = "2.3.2"

[dependencies.chrono]
features = ["serde"]
version = "0.4.19"
